Blasterify.Client/Controllers/BaseController.cs
using Blasterify.Client.Models;
using System.Linq;
using System.Web.Mvc;

namespace Blasterify.Client.Controllers
{
    public class BaseController : Controller
    {
        #region FUNCTIONS
        public bool VerifySession()
        {
            if (Session["ClientUser"] == null)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        public ClientUser GetClientUser()
        {
            return Session["ClientUser"] as ClientUser;
        }

        public void SetCart(Blasterify.Models.Model.PreRentModel cart)
        {
            if (cart != null)
            {
                Session["Cart"] = cart;
            }
        }

        public Blasterify.Models.Model.PreRentModel GetCart()
        {
            if (Session["Cart"] == null)
            {
                return null;
            }

            return Session["Cart"] as Blasterify.Models.Model.PreRentModel;
        }

        public int GetCartCount()
        {
            Blasterify.Models.Model.PreRentModel cart = Session["Cart"] as Blasterify.Models.Model.PreRentModel;

            if (cart == null)
            {
                return 0;
            }
            else
            {
                return cart.PreRentItems.Count;
            }
        }

        #endregion

        #region REQUEST

        [HttpPost]
        public JsonResult GetCartRequest()
        {
            var cart = GetCart();

            return Json(
                new
                {
                    data = cart.PreRentItems.Values.ToList()
                },
                JsonRequestBehavior.AllowGet
            );
        }

        [HttpGet]
        public JsonResult GetCartCountRequest()
        {
            var cart = GetCart();

            if (cart == null)
            {

                return Json(
                    new Result(
                        false,
                        new
                        {
                            Count = 0
                        },
                        "Error"
                    ),
                    JsonRequestBehavior.AllowGet
                );
            }
            else
            {
                return Json(
                    new Result(
                        true,
                        new
                        {
                            Count = cart.PreRentItems != null ? cart.PreRentItems.Count : 0
                        },
                        "Success"
                    ),
                    JsonRequestBehavior.AllowGet
                );
            }
        }

        #endregion
    }
}

Blasterify.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-light bg-black">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand text-warning" href="#!">Blasterify</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link text-warning active" aria-current="page" href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="nav-item"><a class="nav-link text-warning" href="@Url.Action("MyAccount", "Home")">My Account</a></li>

                    @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>*@
                </ul>

                <form class="d-flex">
                    @Html.AntiForgeryToken()
                    <a class="btn btn-outline-warning" href="@Url.Action("Cart", "Home")">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-warning text-dark ms-1 rounded-pill" id="cartCount">0</span>
                    </a>
                </form>
            </div>
        </div>
    </nav>

    @RenderBody()
    <footer>
        <p>&copy; @DateTime.Now.Year - Blasterify</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        function ShowCartCount(count) {
            jQuery.ajax({
                url: '@Url.Action("GetCartCountRequest", "Base")',
                type: 'GET',
                datatype: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    console.log('ShowCartCount', response);
                    if (response.Success) {
                        $("#cartCount").text(response.Data.Count)
                    }
                    else {
                        console.log('ShowCartCount', 'Error');
                    }
                },
            });
        }
    </script>
</body>
</html>

<!--
    if ($("#cartCount").length > 0)
            {

                jQuery.ajax({
                    url: '@Url.Action("GetCartCount", "Home")',
                    type: 'GET',
                    datatype: 'json',
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {
                    $("#cartCount").text(result.carCount)
                    },
                    });

                    }*/
-->